### PR TITLE
Added Quest PowerGUI detection.

### PR DESCRIPTION
**Pull request by ArjanOnwezen**
Added Quest PowerGUI detection.

### CODE REVIEW

**Comment by DosX-dev** [comment]
Thank you. I will rewrite and optimize your detection so that it looks appropriate.

**Comment by DosX-dev** [comment]
[https://github.com/horsicq/Detect-It-Easy/commit/78ce310d8a1aa7169a836003d039e5e60805bc70#diff-9a800164a57208f474febe524c91de06534a75b01a9042fd4a9f21d33bdb3cdf](Done). Can you provide one or more samples?

**Comment by DosX-dev** [comment]
[Done](https://github.com/horsicq/Detect-It-Easy/commit/78ce310d8a1aa7169a836003d039e5e60805bc70#diff-9a800164a57208f474febe524c91de06534a75b01a9042fd4a9f21d33bdb3cdf). Can you provide one or more samples?

**Comment by ArjanOnwezen** [comment]
@DosX-dev  sure, https://github.com/ArjanOnwezen/decompile/tree/main/exe/PowerGUI%20Script%20Editor

Hello-world.exe

**Pull request merged**
