### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Aniketmishra0**

### CODE REVIEW

**Comment by horsicq** [comment]
Thanks a lot!

**Comment by Aniketmishra0** [comment]
@horsicq  Welcome 
Can you add Labels like

Hacktoberfest
Hacktoberfest2022
hacktoberfest-accepted

**Comment by horsicq** [comment]
It will be accepted without the labels. Do not worry. :)

**Comment by horsicq** [comment]
If you need more PRs take a look to the repo: https://github.com/horsicq/XTranslation/tree/master/dicts just take an online translator and make 2-3 new word translations

**Pull request merged**
